modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/LIUKRAST/Repackaged/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://liukrast.net/"
logoFile="${mod_id}.png"
credits=""
authors = "${mod_authors}"
description = '''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="create"
    type="required"
    versionRange="${create_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="deployer"
    type="required"
    versionRange="${deployer_version_range}"
    ordering="NONE"
    side="BOTH"
